services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # .env ファイルの APP_PORT またはデフォルトの 8080 を使用します
      - "${APP_PORT:-8080}:${PORT:-8080}"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
